import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { AppFigure } from "@/components/product-showcase";
export const metadata: Metadata = {title:"The Mac Editor",description:"Explore actual WatchMotion Editor screens: review motion charts, confirm Auto Segments, customize labels, and export datasets."};
export default function MacEditor() { return <div className="container">
  <header className="page-intro"><span className="eyebrow">Built for a closer look</span><h1>Raw motion.<br/>Clear decisions.</h1><p>A dedicated Mac workspace for the part that needs your judgment: what happened, where it happened, and what to call it.</p><Link className="button button-dark" href="/guide/review-and-segment">Learn the editing workflow <ArrowRight size={18}/></Link></header>
  <AppFigure src="/images/mac-editor-dark.png" alt="Actual Mac editor with three activity bursts and the Object Transfer inspector" caption="Actual Mac app · Desk Object Transfer · Illustrative sample data"/>
  <section className="feature-story"><div className="story-heading"><div><span className="eyebrow">01 / Understand the signal</span><h2>See the movement.<br/>Keep the context.</h2></div><div><p>Read acceleration, rotation rate, and attitude side by side in the same recording. Select a range, focus on its detail, then return to the full timeline.</p><Link className="text-link" href="/guide/review-and-segment">Read the charts <ArrowRight size={18}/></Link></div></div></section>
  <section className="feature-story"><div className="story-heading"><div><span className="eyebrow">02 / A first cut, not a final answer</span><h2>Let activity guide<br/>your attention.</h2></div><div><p>Auto Segments suggests active ranges. Review the dashed boundaries, refine them, and confirm only the segments that belong in your work. Suggestions do not automatically recognize or label actions.</p><Link className="text-link" href="/guide/review-and-segment#suggestions">How suggestions work <ArrowRight size={18}/></Link></div></div><AppFigure src="/images/mac-segments.png" alt="Actual Mac Auto Segments suggestion awaiting confirmation" caption="Actual Mac app · A suggestion is reviewed before it becomes a saved snap."/></section>
  <section className="feature-story"><div className="story-heading"><div><span className="eyebrow">03 / Make the vocabulary yours</span><h2>Your labels.<br/>Your way of working.</h2></div><div><p>Customize project labels and colors. Add concise notes, organize labeled snaps into folders, and switch between Light, Dark, and System appearance without changing your workflow.</p><Link className="text-link" href="/guide/label-and-organize">Label and organize <ArrowRight size={18}/></Link></div></div><AppFigure src="/images/mac-editor-light.png" alt="Actual Mac editor in Light appearance with a labeled motion range" caption="Actual Mac app · Light appearance · Illustrative sample data"/></section>
  <section className="feature-story"><div className="story-heading"><div><span className="eyebrow">04 / Keep the next step open</span><h2>A dataset to use.<br/>A project to revisit.</h2></div><div><p>Export reviewed folder contents as CSV or Create ML data. Save a .watchmotion project when you want to preserve your workspace for further editing.</p><Link className="text-link" href="/guide/export-and-save">Choose an export <ArrowRight size={18}/></Link></div></div></section>
</div>; }
