import type { Metadata } from "next";
import { site } from "@/lib/site";
export const metadata: Metadata = {title:"Privacy Policy",description:"How WatchMotion Editor handles local motion recordings, device transfers, exports, website requests, and support correspondence."};
export default function Privacy(){return <div className="container"><article className="prose"><header className="page-intro"><span className="eyebrow">Privacy</span><h1>Your motion.<br/>Your context.</h1><p>This policy explains how the WatchMotion Editor apps, this website, and support correspondence handle information.</p><p className="policy-meta">Last updated: {site.policyDate}<br/>Operator: {site.operator} · <a href={`mailto:${site.email}`}>{site.email}</a></p></header>
 <section><h2>1. Information in the apps</h2><p>WatchMotion Editor records motion sensor samples on Apple Watch, including acceleration, rotation rate, gravity, orientation, and timestamps. Recordings can include session metadata such as duration and sample count. The apps store recordings and editing information locally on your devices.</p><p>You may choose to add recording names, labels, notes, and participant information. Optional participant fields can include a name or nickname, gender, age group, height, dominant hand, experience level, and a memo. Only enter information you need and have permission to use.</p></section>
 <section><h2>2. How that information is used</h2><p>The apps use this information to show motion charts, suggest activity ranges, save your annotations, organize projects, and create exports you request. Auto Segments analysis runs in the Mac app. A WatchMotion Editor account is not required.</p><p>The current apps do not include advertising or a third-party analytics SDK, and they do not upload your recordings to an operator-run cloud service. This does not prevent you from intentionally exporting or sharing a file, or from using operating-system backup services.</p></section>
 <section><h2>3. Device connections and permissions</h2><p>The Watch app sends recordings to its paired iPhone using Apple’s device connectivity services. iPhone-to-Mac transfer uses a local peer connection; you approve the iPhone connection on Mac. Permissions such as motion access and local network access support recording and device discovery. You can manage permissions in your device settings, but disabling them can prevent the related feature from working.</p><p>The Watch app must remain open while recording. Leaving it saves and stops recording; it is not designed for continuous background monitoring.</p></section>
 <section><h2>4. Exports, backups, and deletion</h2><p>Exported CSV, Create ML data, and project files can include motion samples and the metadata you choose to include. Review your export settings before sharing, especially if notes or participant fields contain personal information. Exports are separate copies outside the app’s control.</p><p>Recordings and annotations remain on your devices until you remove them. Watch transfer files are retained until the iPhone confirms import, or until you delete them. Deleting a local copy does not erase copies on another device, files you have exported, or backups held by another service. Manage those copies separately.</p><p>If you save files to iCloud Drive or another synced folder, that provider’s terms and privacy settings also apply.</p></section>
 <section><h2>5. This website</h2><p>You can read this website without creating an account. We have not added advertising trackers, analytics scripts, or a contact form. Fonts and website images are served as site assets; there are no embedded third-party videos.</p><p>When hosted on Vercel, requests are processed by Vercel to deliver and protect the site. Technical information such as IP address, request path, browser information, and request time may be processed in hosting and security systems. This is separate from the motion recordings stored by the apps. See <a href="https://vercel.com/legal/privacy-policy">Vercel’s Privacy Policy</a> for its handling of personal information.</p></section>
 <section><h2>6. When you contact support</h2><p>If you email support, we receive your email address and the information you choose to send, including message text and any attachments. We use it to respond, investigate issues, and maintain relevant support records. Correspondence is handled through our email provider; do not send recordings or sensitive participant information unless necessary and agreed in advance.</p><p>Support information is kept while needed to resolve and follow up on the request, subject to applicable recordkeeping requirements. Contact us to request access, correction, or deletion of support information. We cannot remotely access or delete recordings stored only on your devices.</p></section>
 <section><h2>7. Your choices and other people’s information</h2><p>You control whether to record, add optional context, transfer files, or export data. If you record or describe another person, obtain any permission required for your situation. Take particular care with children’s information and avoid including unnecessary identifying details.</p><p>Depending on where you live, you may have rights regarding personal information we hold, including access, correction, and deletion. Contact us below to make a request or raise a privacy concern.</p></section>
 <section><h2>8. Updates and contact</h2><p>We may update this policy when the apps, website, or information-handling practices change. The date at the top identifies the latest update.</p><p>For privacy questions, contact {site.operator} at <a href={`mailto:${site.email}`}>{site.email}</a>.</p></section>
 </article></div>;}
