import Link from "next/link";
import { ProductShowcase } from "@/components/product-showcase";
import { ArrowRight, ArrowUpRight, Watch, Smartphone, Monitor, MoveHorizontal, Tags, FolderOutput } from "lucide-react";
import { site, storeLinks } from "@/lib/site";

export default function Home() {
  const stores = storeLinks();
  return <>
    <section className="home-hero"><div className="container">
      <div className="hero-topline"><span className="eyebrow"><span className="status-dot"/> A motion data workspace</span><span className="hero-platforms">APPLE WATCH / IPHONE / MAC</span></div>
      <div className="hero-copy"><h1>Every movement.<br/>A story in data.</h1><div className="hero-side"><h2>Capture on Watch. Refine on Mac.</h2><p>Turn everyday motion into a dataset you understand. Record on your wrist, review on iPhone, and give each movement context on Mac.</p><Link className="text-link" href="/guide/getting-started">Discover the workflow <ArrowUpRight size={19}/></Link></div></div>
    </div></section>
    <ProductShowcase/>
    <section className="section" id="workflow"><div className="container"><div className="section-heading"><div><span className="eyebrow">01 / THE WORKFLOW</span><h2>From your wrist.<br/>To your next idea.</h2></div><p>Each device has a job. Together, they take you from a raw recording to a dataset you understand.</p></div><div className="device-grid">
      {[{icon:Watch,n:"01",title:"Capture on Watch",text:"Record acceleration, rotation rate, and attitude as you move. Keep the app open while recording.",os:site.minOS.watch+" or later"},{icon:Smartphone,n:"02",title:"Review on iPhone",text:"Check the recording, inspect its motion charts, add a note, and send it to your Mac.",os:site.minOS.iphone+" or later"},{icon:Monitor,n:"03",title:"Refine on Mac",text:"Find activity ranges, adjust boundaries, apply labels, and export a focused dataset.",os:site.minOS.mac+" or later"}].map(({icon:Icon,n,title,text,os})=><article className="device-card" key={n}><div className="card-top"><Icon size={30} strokeWidth={1.4}/><span>{n}</span></div><h3>{title}</h3><p>{text}</p><span className="device-os">{os}</span></article>)}
    </div><p className="subtle-note">The complete workflow requires an Apple Watch paired with an iPhone, plus a Mac. Apps are installed on each device.</p></div></section>
    <section className="section soft-section"><div className="container"><div className="section-heading"><div><span className="eyebrow">02 / MADE FOR THE DETAILS</span><h2>Less searching.<br/>More understanding.</h2></div><Link className="text-link" href="/mac-editor">Take a closer look <ArrowRight size={18}/></Link></div><div className="feature-columns">
      {[{icon:MoveHorizontal,title:"A useful first cut",text:"Auto Segments suggests activity ranges. You decide what to keep and where each segment begins and ends."},{icon:Tags,title:"Labels that fit your work",text:"Create a project label vocabulary, add context with notes, and keep your annotations connected to the recording."},{icon:FolderOutput,title:"Ready for the next step",text:"Organize labeled segments into folders. Export CSV or Create ML datasets, or save a project to continue later."}].map(({icon:Icon,title,text})=><article key={title}><Icon className="coral" size={26}/><h3>{title}</h3><p>{text}</p></article>)}
    </div></div></section>
    <section className="section"><div className="container guide-banner"><div><span className="eyebrow">A SMALL MOVEMENT. A COMPLETE WALKTHROUGH.</span><h2>Your first labeled<br/>object transfer.</h2><p>Follow a desk-based example, from recording a movement to exporting its labeled samples.</p><Link className="button button-dark" href="/guide">Open the user guide <ArrowRight size={18}/></Link></div><div className="example-label"><span>EXAMPLE PROJECT</span><h3>Everyday<br/>Hand Motions</h3><div className="label-chip"><span/> Object Transfer</div><p>Pick up. Move. Set down. Pause.</p></div></div></section>
    <section className="download-section" id="download"><div className="container download-inner"><div><span className="eyebrow">WATCHMOTION EDITOR</span><h2>Your next dataset<br/>starts with a movement.</h2><p>For Apple Watch, iPhone, and Mac.</p></div><div className="download-actions">{stores.iphone || stores.mac ? <>{stores.iphone && <a className="button button-light" href={stores.iphone}>Get iPhone & Watch apps <ArrowUpRight size={18}/></a>}{stores.mac && <a className="button button-light" href={stores.mac}>Get the Mac app <ArrowUpRight size={18}/></a>}</> : <><span className="coming-soon"><span className="status-dot"/> Coming to the App Store</span><p>We’re preparing the first release.<br/>Explore the workflow while we get ready.</p><Link className="text-link light-link" href="/guide/getting-started">Read the setup guide <ArrowRight size={18}/></Link></>}</div></div></section>
  </>;
}
